-- This file is retired. The one schema for the whole project now lives at
-- `aval/contracts/fixtures/schema.sql` — that is the file `compose.yaml`
-- mounts into `/docker-entrypoint-initdb.d/`, and the file `src/agent/db.py`
-- reads at runtime (see `_load_schema()` there). Nothing loads this file any
-- more; it is kept only so a stale reference to this path fails loudly by
-- finding an obviously-empty schema rather than silently reintroducing a
-- second, drifting definition of the database.
