"""Issuer key material and the published JWKS.

Decision #15, two tiers:

* **Secret Manager** holds the Ed25519 PEM that signs mandates, and the P-256
  PEM that signs AP2 Checkout JWTs. Operational keys, cheap to rotate.
* **Cloud KMS** (`EC_SIGN_ED25519`) signs audit roots — that is Dev 2's, not
  here. Those are the keys whose custody gets cross-examined, so the HSM holds
  them.

In development the PEMs come from `./secrets/`, which is gitignored. There is
a deliberate asymmetry: dev keys are generated on demand, production keys are
never generated by this code — a missing secret in GCP is an error, not an
invitation to invent one.

Rotation: `kid` is incremental and the JWKS publishes current + previous, so a
mandate signed before a rotation still verifies for 24h (decision #6).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

from jwcrypto import jwk

from trustlib.jose import generate_pem_pair, key_from_pem, public_jwk

from ..config import Settings, settings

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class SigningKey:
    kid: str
    key: jwk.JWK
    alg: str


class KeyStore:
    """Loads signing keys and publishes their public halves as a JWK Set."""

    def __init__(self, config: Settings | None = None) -> None:
        self._config = config or settings()
        self._issuer: SigningKey | None = None
        self._merchant: SigningKey | None = None
        self._retired: list[SigningKey] = []

    # -- loading -----------------------------------------------------------
    def issuer_key(self) -> SigningKey:
        """Ed25519 key that signs mandate SD-JWTs."""
        if self._issuer is None:
            pem = self._read_pem(self._config.issuer_key_secret,
                                 "issuer_ed25519.pem", curve="Ed25519")
            self._issuer = SigningKey(
                kid=self._config.issuer_kid, key=key_from_pem(pem), alg="EdDSA")
        return self._issuer

    def merchant_key(self) -> SigningKey:
        """P-256 key for AP2 Checkout JWTs.

        Separate from the issuer key by specification, not preference: AP2
        forbids a deterministic signature on the hash-bound Checkout JWT
        (decision 0023), and Ed25519 is deterministic.
        """
        if self._merchant is None:
            pem = self._read_pem(self._config.merchant_key_secret,
                                 "merchant_es256.pem", curve="P-256")
            self._merchant = SigningKey(kid="m1", key=key_from_pem(pem),
                                        alg="ES256")
        return self._merchant

    def _read_pem(self, secret_name: str, filename: str, *, curve: str) -> bytes:
        if self._config.gcp_project:
            return self._read_from_secret_manager(secret_name)
        return self._read_from_disk(filename, curve=curve)

    def _read_from_secret_manager(self, secret_name: str) -> bytes:
        from google.cloud import secretmanager

        client = secretmanager.SecretManagerServiceClient()
        path = (f"projects/{self._config.gcp_project}"
                f"/secrets/{secret_name}/versions/latest")
        log.info("loading signing key from Secret Manager: %s", secret_name)
        return client.access_secret_version(name=path).payload.data

    def _read_from_disk(self, filename: str, *, curve: str) -> bytes:
        """Development only. Generates the key on first use.

        Generating on demand is safe here because `secrets/` is gitignored and
        never leaves the machine; the same code path in GCP would silently
        create an issuer nobody trusts, which is why it is not reachable there.
        """
        directory = Path(self._config.secrets_dir)
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / filename

        if not path.exists():
            pem, _ = generate_pem_pair(curve)
            path.write_bytes(pem)
            path.chmod(0o600)
            log.warning("generated a DEVELOPMENT %s key at %s — "
                        "production keys come from Secret Manager", curve, path)
        return path.read_bytes()

    # -- publishing --------------------------------------------------------
    def jwks(self) -> dict:
        """Public keys, for anyone verifying without trusting us (decision #6).

        Carries both the issuer's EdDSA key and the merchant's ES256 key: a
        verifier checking a Checkout JWT needs the latter, and one JWKS is
        simpler to consume than two endpoints.
        """
        keys = [
            self._advertise(self.issuer_key(), use="sig"),
            self._advertise(self.merchant_key(), use="sig"),
        ]
        keys.extend(self._advertise(k, use="sig") for k in self._retired)
        return {"keys": keys}

    @staticmethod
    def _advertise(signing_key: SigningKey, *, use: str) -> dict:
        published = public_jwk(signing_key.key, kid=signing_key.kid)
        published["use"] = use
        published["alg"] = signing_key.alg
        return published

    def verification_keys(self) -> dict[str, jwk.JWK]:
        """`kid -> JWK`, the shape `sdjwt.verify` expects."""
        keys = {
            self.issuer_key().kid: self.issuer_key().key,
            self.merchant_key().kid: self.merchant_key().key,
        }
        keys.update({k.kid: k.key for k in self._retired})
        return keys


_store: KeyStore | None = None


def key_store() -> KeyStore:
    global _store
    if _store is None:
        _store = KeyStore()
    return _store
